# Generated by Django 4.2.13 on 2024-07-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
